---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tagreflector.operator.pthomison.com
  resources:
  - tagreflectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tagreflector.operator.pthomison.com
  resources:
  - tagreflectors/finalizers
  verbs:
  - update
- apiGroups:
  - tagreflector.operator.pthomison.com
  resources:
  - tagreflectors/status
  verbs:
  - get
  - patch
  - update
