apiVersion: tagreflector.operator.pthomison.com/v1alpha1
kind: TagReflector
metadata:
  labels:
    app.kubernetes.io/name: tagreflector
    app.kubernetes.io/instance: tagreflector-sample
    app.kubernetes.io/part-of: tag-watcher
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tag-watcher
  name: tagreflector-sample
spec:
  repository: docker.io/library/python
  destination: 127.0.0.1:15555/python
  suffix: "testing"
  regex: 
    match: "3.9(.*)-alpine(.*)"
    ignore: "windows"
  actions:
  - command:
      args:
      - echo
      - "hello world"
